services:
  - type: web
    name: techdom-app
    env: python
    plan: starter
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: streamlit run apps/streamlit/main.py --server.address 0.0.0.0 --server.port $PORT
    autoDeploy: true
    healthCheckPath: /
